name: AsteriaSMP
author: RRRamiro
version: 2.0.5
main: net.randompvp.asteria.Asteria
api-version: 1.17

commands:
  r:
    description: Reply to someone
  cancelrestart:
    description: Cancel Restart
  shrug:
    description: Shrugs for you